### ISSUE TITLE
Cannot preview the app demo

### ISSUE THREAD

**Issue by ihsanrawi** [fromtexas/react-native-budget-app#1]
https://expo.io/@fromtexas/budgety  states that 

'This project needs an update
This project uses Expo SDK v24.0.0. If you want to open this project, the author will need to update the project's SDK version.'

Could you update it. Would love to see the app working

**Comment by fromtexas** [comment]
Check the link again.

**Comment by ihsanrawi** [comment]
Thanks its working now
